### ISSUE TITLE
Simplify list of HD OBD devices

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#26] opened 2017-06-21 15:34 UTC
**The component ID content was:**
2017-06-06T14:13:04.906 Global Component Identification Request
2017-06-06T14:13:04.906 18EAFFF9 EB FE 00 (TX)
2017-06-06T14:13:06.156 18FEEBE9 49 4E 54 20 20 2A 34 30 36 31 39 36 38 43 32 2A 30 30 30 41 41 41 2A 2A
Component Identification from Door Controller #3 (233): Make: INT, Model: 4061968C2, Serial Number: 000AAA, Unit Number:
2017-06-06T14:13:06.156 18FEEBEA 49 4E 54 20 20 2A 34 30 36 31 39 36 38 43 32 2A 30 30 30 41 42 42 2A 2A
Component Identification from Door Controller #4 (234): Make: INT, Model: 4061968C2, Serial Number: 000ABB, Unit Number:
2017-06-06T14:13:06.156 18FEEB0B 4D 45 52 57 42 2A 41 42 53 20 34 30 30 38 36 34 35 31 36 30 2A 34 34 35 30 30 35 39 33 35 32 2A 2A
Component Identification from Brakes - System Controller (11): Make: MERWB, Model: ABS 4008645160, Serial Number: 4450059352, Unit Number:
2017-06-06T14:13:06.156 18FEEB17 49 4E 54 2A 34 30 36 32 38 37 37 43 31 2A 39 38 38 38 34 36 30 30 31 36 33 37 38 36 30 2A 2A
Component Identification from Instrument Cluster #1 (23): Make: INT, Model: 4062877C1, Serial Number: 988846001637860, Unit Number:
2017-06-06T14:13:06.156 1CFEEB19 49 4E 54 20 20 2A 34 30 36 35 33 33 31 43 33 2A 30 30 30 30 30 30 30 30 30 30 30 32 32 37 33 39 2A 2A
Component Identification from Passenger-Operator Climate Control #1 (25): Make: INT, Model: 4065331C3, Serial Number: 0000000000022739, Unit Number:
2017-06-06T14:13:06.158 18FEEB97 49 4E 54 20 20 2A 20 34 30 35 37 36 38 39 43 31 2A 4D 31 37 30 37 35 35 34 31 30 39 32 30 31 30 30 33 34 2A 2A
Component Identification from Reserved for future assignment 151 (151): Make: INT, Model: 4057689C1, Serial Number: M17075541092010034, Unit Number:
2017-06-06T14:13:06.158 18FEEB37 49 4E 54 20 20 2A 20 34 30 38 36 38 36 38 43 31 2A 4C 31 37 30 37 36 35 34 31 30 39 32 30 30 30 30 31 37 2A 2A
Component Identification from Lighting - Operator Controls (55): Make: INT, Model: 4086868C1, Serial Number: L17076541092000017, Unit Number:
2017-06-06T14:13:06.158 1CFEEB00 43 4D 4D 4E 53 2A 36 42 20 75 31 33 44 30 36 37 30 30 30 30 30 30 30 2A 37 34 31 31 34 32 35 30 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A
Component Identification from Engine #1 (0): Make: CMMNS, Model: 6B u13D0670000000, Serial Number: 74114250, Unit Number:
*******************************************************
**Abridged this might look like:**
2017-06-06T14:13:04.906 Global Component Identification Request
14:13:04.906 18EAFFF9 EB FE 00 (TX)
14:13:06.156 18FEEBE9 49 4E 54 20 20 2A 34 30 36 31 39 36 38 43 32 2A 30 30 30 41 41 41 2A 2A
Found: Door Controller #3 (233): Make: INT, Model: 4061968C2, Serial: 000AAA, Unit:
14:13:06.156 18FEEBEA 49 4E 54 20 20 2A 34 30 36 31 39 36 38 43 32 2A 30 30 30 41 42 42 2A 2A
Found: Door Controller #4 (234): Make: INT, Model: 4061968C2, Serial: 000ABB, Unit:
14:13:06.156 18FEEB0B 4D 45 52 57 42 2A 41 42 53 20 34 30 30 38 36 34 35 31 36 30 2A 34 34 35 30 30 35 39 33 35 32 2A 2A
Found: Brakes - System Controller (11): Make: MERWB, Model: ABS 4008645160, Serial: 4450059352, Unit:
14:13:06.156 18FEEB17 49 4E 54 2A 34 30 36 32 38 37 37 43 31 2A 39 38 38 38 34 36 30 30 31 36 33 37 38 36 30 2A 2A
Found: Instrument Cluster #1 (23): Make: INT, Model: 4062877C1, Serial: 988846001637860, Unit:
14:13:06.156 1CFEEB19 49 4E 54 20 20 2A 34 30 36 35 33 33 31 43 33 2A 30 30 30 30 30 30 30 30 30 30 30 32 32 37 33 39 2A 2A
Found: Passenger-Operator Climate Control #1 (25): Make: INT, Model: 4065331C3, Serial: 0000000000022739, Unit:
14:13:06.158 18FEEB97 49 4E 54 20 20 2A 20 34 30 35 37 36 38 39 43 31 2A 4D 31 37 30 37 35 35 34 31 30 39 32 30 31 30 30 33 34 2A 2A
Found: Reserved for future assignment 151 (151): Make: INT, Model: 4057689C1, Serial: M17075541092010034, Unit:
14:13:06.158 18FEEB37 49 4E 54 20 20 2A 20 34 30 38 36 38 36 38 43 31 2A 4C 31 37 30 37 36 35 34 31 30 39 32 30 30 30 30 31 37 2A 2A
Found: Lighting - Operator Controls (55): Make: INT, Model: 4086868C1, Serial: L17076541092000017, Unit:
14:13:06.158 1CFEEB00 43 4D 4D 4E 53 2A 36 42 20 75 31 33 44 30 36 37 30 30 30 30 30 30 30 2A 37 34 31 31 34 32 35 30 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A 2A
Found: Engine #1 (0): Make: CMMNS, Model: 6B u13D0670000000, Serial: 74114250, Unit:

**Comment by gumbelmj** [comment] 2017-06-21 15:37
So the requested change is to remove the date from most timestamps?

**Comment by joekartje** [comment] 2017-06-21 15:40
Yes.  But it was agreed to be a low priority.  There's more detail on all
these issues I'm now entering into GitHub in the attached file from
yesterday's meeting.

**Comment by gumbelmj** [comment] 2017-06-21 20:10
This is a duplicate of Issue #24

**Comment by joekartje** [comment] 2017-06-21 20:17
Besides removing the date from the timestamp, issue 26 had a few other
simplifying changes.  For example:

change "Component Identification from " to "Found: "
change "Serial Number" to "Number"
change "Unit Number" to "Number"

**Comment by gumbelmj** [comment] 2017-06-22 15:04
The reporting was condensed to remove"Number" and change "Component Identification" to "Found"  The date/time changes will be performed with issue #24

**Closed as completed by gumbelmj** 2017-06-22 15:04 UTC
