### ISSUE TITLE
Single ended tests shown as failed should be shown as passing.

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#39] opened 2017-08-24 15:09 UTC
Test minimums and maximums that contain 0xFFFF indicate a one tailed test where the minimum or maximum is not considered these single ended tests have the form t < b or a < t, and are not a two tail test where a < t < b.  The identification of single ended test is defined in Table 5 of SAE J1939-73.

The linked issue form is https://drive.google.com/open?id=0BzIQ48EeW5tTQ1dsQlV0TGFvdEk

**Comment by gumbelmj** [comment] 2017-08-24 15:18
This is a duplicate of Issue #34

**Closed as completed by gumbelmj** 2017-08-24 15:18 UTC
